development:
  adapter: postgresql
  database: myrecipes_development
  username: postgres
  password: 12345
  host: localhost
  port: 5433

test:
  adapter: postgresql
  database: myrecipes_test
  username: postgres
  password: 12345
  host: localhost
  port: 5433