
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myrecipes_development

test:
  <<: *default
  database: myrecipes_test
production:
  <<: *default
  database: myrecipes_production
  username: myrecipes
  password: <%= ENV['MYRECIPES_DATABASE_PASSWORD'] %>