development:
  adapter: postgresql
  database: myrecipes_development
  username: postgres
  password: admin123
  host: localhost
  port: 5432
  prepared_statements: false

test:
  adapter: postgresql
  database: myrecipes_test
  username: postgres
  password: admin123
  host: localhost
  port: 5432
  prepared_statements: false
